# Generated by Django 3.2 on 2021-05-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BonbuNetIncrease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bugbu_bonbu', models.IntegerField()),
                ('dongbu_bonbu', models.IntegerField()),
                ('gangnam_bonbu', models.IntegerField()),
                ('daegu_gyeongbug', models.IntegerField()),
                ('busan_gyeongnam', models.IntegerField()),
                ('seobu_bonbu', models.IntegerField()),
                ('jeonnam_jeonbug', models.IntegerField()),
                ('jesu_bonbu', models.IntegerField()),
                ('chungnam_chungbug', models.IntegerField()),
            ],
            options={
                'db_table': 'bonbu_net_increase',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='JisaNetIncrease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Gangneung_jisa', models.IntegerField()),
                ('Goyang_jisa', models.IntegerField()),
                ('Gwangin_jisa', models.IntegerField()),
                ('Gwanghwamun_jisa', models.IntegerField()),
                ('Guri_jisa', models.IntegerField()),
                ('Nowon_jisa', models.IntegerField()),
                ('Seodaemun_jisa', models.IntegerField()),
                ('Wonju_jisa', models.IntegerField()),
                ('Uijeongbu_jisa', models.IntegerField()),
                ('Chuncheon_jisa', models.IntegerField()),
            ],
            options={
                'db_table': 'jisa_net_increase',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='RsaiJojik',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sysdate', models.DateField()),
                ('product', models.CharField(max_length=10)),
                ('jojik', models.CharField(max_length=10)),
                ('this_hj_count', models.IntegerField()),
                ('this_hj_ratio', models.FloatField()),
                ('that_hj_count', models.IntegerField()),
                ('that_hj_ratio', models.FloatField()),
                ('up_ratio', models.FloatField()),
                ('rank', models.FloatField()),
            ],
            options={
                'db_table': 'rsai_jojik',
                'ordering': ['id'],
            },
        ),
    ]
