# Generated by Django 3.2 on 2021-05-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rsai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Gangneung_jisa', models.IntegerField()),
                ('Goyang_jisa', models.IntegerField()),
                ('Gwangin_jisa', models.IntegerField()),
                ('Gwanghwamun_jisa', models.IntegerField()),
                ('Guri_jisa', models.IntegerField()),
                ('Nowon_jisa', models.IntegerField()),
                ('Seodaemun_jisa', models.IntegerField()),
                ('Wonju_jisa', models.IntegerField()),
                ('Uijeongbu_jisa', models.IntegerField()),
                ('Chuncheon_jisa', models.IntegerField()),
            ],
            options={
                'db_table': 'jisa_net_increase',
                'ordering': ['date'],
            },
        ),
    ]
