# Generated by Django 3.2 on 2021-04-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSAI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsai',
            name='etc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
