# Generated by Django 3.2 on 2021-04-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSAI', '0002_alter_rsai_etc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsai',
            name='etc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
